{% set version = "0.14.0" %}

package:
  name: poliastro
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/poliastro/poliastro/archive/v{{ version }}.tar.gz
  md5: c08cdb0acb0176fb10638b7c02dd62a2

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6,<3.9
    - pip
    - flit

  run:
    - python >=3.6,<3.9
    - numpy >=1.10
    - scipy >=1.4
    - numba >=0.46,<0.49
    - astropy >=3.2,<5
    - jplephem
    - matplotlib-base >=2.0,!=3.0.1
    - pandas
    - plotly >=4.0,<5
    - astroquery >=0.3.9
    - notebook
    - cached-property

test:
  imports:
    - poliastro
    - poliastro.constants
    - poliastro.twobody
    - poliastro.threebody
    - poliastro.iod
    - poliastro.frames
    - poliastro.plotting

about:
  home: https://poliastro.github.io/
  license: MIT
  license_file: COPYING
  summary: Python package for Orbital Mechanics

extra:
  recipe-maintainers:
    - astrojuanlu
