travis:
  secure:
    BINSTAR_TOKEN: LtJHvB3IQ+yPHhlMcA3NpUB8QAqeTL15u9C7kSP6XTE+Jv0KpdwMsiTZMopgwNK9LhwqoCImM16Hx+QDenog2aOMzh3JG1F57xCfok4YIRyle+t+eTtNQyhN5YuSt339+EjBJAB9UmcrjoO5dkP8rA2P5rXxQlVgc32Pa5dAepuozFypGL7AVsMEGZ/qad0t4JYCof10VWFMvsHpKvPTR65fHYkBNohPL6UuhIQLfodbRBeFQNUmNtLrZcEzSbPGnQkNlI85wgohC+IVBIRdDaMKQEGh7AHNFFDiDoqqMgauv8xKMR7uxk7McWSZuGGUxMQ8pVQF2809ZhGyYYqRdEphLyDtjJu/yKLNKXC+yx7V7dJzObolAqYJS1hsKwObhG8j6J0+31rzeIeznbTe30Z9bxDaMyD3wpa07bNgHvZYNO4HgXdE9kcS7aFkQiz2JKKSU9cKiQABgqbk0iMnMLaHptlFsCULcFrsR9B3cPpeDZzUCecSNjQnNyGaHNHmBt50EIc37zHtdvK3OHCX+3bUdFIDGPllVoeC44qN/VUpWkr6m51fl/Grk2/rAlHyo/1YwTKiBff0SI9hVIILqt1r0FqxrH+9+C57UNC1MFsYJlC3dlINep+mhmDU0nqlCE905t6zM04fvOLWL5hdLyBO7KKbswK1OVsHvdpIZBA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
